//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicLibray
{
    using System;
    using System.Collections.Generic;
    
    public partial class Band
    {
        public Band()
        {
            this.Albums = new HashSet<Album>();
            this.Genres = new HashSet<Genre>();
            this.Labels = new HashSet<Label>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int GenreId { get; set; }
    
        public virtual ICollection<Album> Albums { get; set; }
        public virtual Country Country { get; set; }
        public virtual ICollection<Genre> Genres { get; set; }
        public virtual ICollection<Label> Labels { get; set; }
    }
}
