//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicLibray
{
    using System;
    using System.Collections.Generic;
    
    public partial class Genre
    {
        public Genre()
        {
            this.Bands1 = new HashSet<Band>();
            this.Albums = new HashSet<Album>();
            this.Labels = new HashSet<Label>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Band> Bands1 { get; set; }
        public virtual ICollection<Album> Albums { get; set; }
        public virtual ICollection<Label> Labels { get; set; }
    }
}
