//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicLibray
{
    using System;
    using System.Collections.Generic;
    
    public partial class Label
    {
        public Label()
        {
            this.Bands = new HashSet<Band>();
            this.Albums = new HashSet<Album>();
            this.Genres = new HashSet<Genre>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public int CountryId { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<Band> Bands { get; set; }
        public virtual ICollection<Album> Albums { get; set; }
        public virtual ICollection<Genre> Genres { get; set; }
    }
}
